Unit Test - pkg/verification
sigstore/timestamp-authority pull request #157
Opened 2022-11-28 21:50 UTC by neilnaveen

Signed-off-by: Neil Naveen <42328488+neilnaveen@users.noreply.github.com>

#### Summary
- included additional tests for pkg/verification for better coverage

#### Release Note
NONE

#### Documentation
NONE

2022-11-28 22:32 UTC, haydentherapper requested changes
Given these are private functions, I don't see a need to add nil checks.

`certPool` could be nil, but I don't see a need to check in VerifyTimestampResponse if this is nil because it should not be user-controlled, and the downstream libraries can handle a nil certPool anyways.

2022-11-29 01:47 UTC, neilnaveen commented
> Given these are private functions, I don't see a need to add nil checks.
> 
> `certPool` could be nil, but I don't see a need to check in VerifyTimestampResponse if this is nil because it should not be user-controlled, and the downstream libraries can handle a nil certPool anyways.

My take on this is that the code should follow defense in depth. What if downstream libraries miss the nil check and it panics? 

I also feel that adding these additional checks does not add additional complexity. 

Thoughts?

2022-11-29 02:42 UTC, haydentherapper commented
Downstream libraries can't use private functions, so no concerns there. Panics are also more useful than errors in this context, it shows where an error occurred with a stack trace. I'd like to avoid excessive nil checks even if it doesn't add complexity, because it suggests that values could be nil when either they can't or a mistake was made.

2022-12-02 00:06 UTC, neilnaveen commented
I have removed all nil cases that I added in verify.go and verify_test.go

2022-12-02 20:42 UTC, haydentherapper commented on pkg/verification/verify_test.go
> +	client2 "github.com/sigstore/timestamp-authority/pkg/generated/client"
```suggestion
	tsaClient "github.com/sigstore/timestamp-authority/pkg/generated/client"
```

2022-12-02 20:42 UTC, haydentherapper commented on pkg/verification/verify_test.go
> +			respBytes, certPool, err := getTimestampData(tt.args.tsmessage, c)
Lint error of not checking `err`

2022-12-12 22:04 UTC, haydentherapper commented
PR 181 should cover this, as it adds additional unit tests for verification

2022-12-12 22:04 UTC, closed without merging